// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlncesiusutvubwlqkar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsbmNlc2l1c3V0dnVid2xxa2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTMxOTAsImV4cCI6MjA2NDQyOTE5MH0.2y4avQa_3yHhLMpKb7clYTMEN6n39fh2PtNBp6LOCpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);